#pragma once

enum {
    ID_TEXTCTRL_HOUSE_PRICE = 301,
    ID_TEXTCTRL_HOUSE_SQUARE,
    ID_TEXTCRTL_TOTAL_LOAN,
    ID_TEXTCTRL_PERCENTAGE_POINT,

    ID_CHOICE_LTV,
    ID_CHOICE_LTY,
    ID_CHOICE_CALCULATE_TYPE,
    ID_CHOICE_INTEREST_TYPE,

    ID_TEXTCTRL_CHOSEN_TYPE_SHOW_INTEREST,
    ID_TEXTCTRL_SHOW_INTEREST,
    ID_TEXTCTRL_SHOW_POINT,
    ID_TEXTCTRL_SHOW_RESULT,

    ID_CHECKBOX_REPAYTYPE_PRINCIPAL_INTEREST,   //等额本息
    ID_CHECKBOX_REPAYTYPE_PRINCIPAL,            //等额本金

    ID_BUTTON_ACTION,
    ID_BUTTON_CLEAR,

    ID_INTEREST,
};